# Generated by Django 5.2.13 on 2026-05-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('alignment', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('detail_url', models.URLField(blank=True)),
                ('ac', models.CharField(blank=True, max_length=50)),
                ('hp', models.CharField(blank=True, max_length=100)),
                ('speed', models.CharField(blank=True, max_length=200)),
                ('initiative', models.CharField(blank=True, max_length=50)),
                ('cr', models.CharField(blank=True, max_length=50)),
                ('strength', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dexterity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('constitution', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('intelligence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wisdom', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('charisma', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('immunities', models.CharField(blank=True, max_length=300)),
                ('senses', models.CharField(blank=True, max_length=300)),
                ('languages', models.CharField(blank=True, max_length=300)),
                ('traits', models.TextField(blank=True)),
                ('actions', models.TextField(blank=True)),
                ('bonus_actions', models.TextField(blank=True)),
                ('reactions', models.TextField(blank=True)),
                ('legendary_actions', models.TextField(blank=True)),
                ('resistances', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('habitat', models.CharField(blank=True, max_length=200)),
                ('treasure', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
