# Generated by Django 5.2.13 on 2026-05-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='mythic_actions',
        ),
    ]
